import { Inter } from "next/font/google";
import "./globals.css";

//-------CONTEXTS------
import { FutureProvider } from "@/context/FutureContext";
import { OptionsProvider } from "@/context/OptionsContext";
import { ActiveOiProvider } from "@/context/ActiveOIContext";
import { NiftyFutureProvider } from "@/context/NiftyFutureContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Algo Trading",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {
          <FutureProvider>
            <OptionsProvider>
              <ActiveOiProvider>
                <NiftyFutureProvider>{children}</NiftyFutureProvider>
              </ActiveOiProvider>
            </OptionsProvider>
          </FutureProvider>
        }
      </body>
    </html>
  );
}
